app_annotations:
    # loads routes from the PHP annotations of the controllers found in that directory
    resource: '../src/Zard/FrontBundle/Controller/'
    type:     annotation
    prefix:
        es: '' # don't prefix URLs for English, the default locale
        en: '/en'
    #    jp: '/jp'
    